# Generated by Django 2.0.4 on 2018-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dpi', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=12)),
                ('coordenadas', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('emergencia', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
